CONNECTION_STRING: fake connection string
ENDPOINT: https://azwepersonal0001.blob.core.windows.net/album

spring:
  codec:
    max-in-memory-size: 10MB
  cloud:
    azure:
      storage:
        account-name: azwepersonal0001
        account-key: ${AZ_STORAGE_ACCOUNT_KEY}
server:
  error:
    include-message: always
